// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYbdHz52hKhCt4L4o4MKx2Oe5aNPl-ts',
    appId: '1:197340792434:web:07ff1c3717e8b3c3dce4eb',
    messagingSenderId: '197340792434',
    projectId: 'mygarage-thiva',
    authDomain: 'mygarage-thiva.firebaseapp.com',
    storageBucket: 'mygarage-thiva.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMoCGDdorpkej2T-tyYy0H-PB_VqstYU',
    appId: '1:197340792434:android:b9417eab3ade2099dce4eb',
    messagingSenderId: '197340792434',
    projectId: 'mygarage-thiva',
    storageBucket: 'mygarage-thiva.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5GtdERVPymr5qaDSD5CYEr3LY3wgknuk',
    appId: '1:197340792434:ios:85c272477828f18bdce4eb',
    messagingSenderId: '197340792434',
    projectId: 'mygarage-thiva',
    storageBucket: 'mygarage-thiva.firebasestorage.app',
    iosBundleId: 'com.autosync.autosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5GtdERVPymr5qaDSD5CYEr3LY3wgknuk',
    appId: '1:197340792434:ios:85c272477828f18bdce4eb',
    messagingSenderId: '197340792434',
    projectId: 'mygarage-thiva',
    storageBucket: 'mygarage-thiva.firebasestorage.app',
    iosBundleId: 'com.autosync.autosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYbdHz52hKhCt4L4o4MKx2Oe5aNPl-ts',
    appId: '1:197340792434:web:b1819023764adbb5dce4eb',
    messagingSenderId: '197340792434',
    projectId: 'mygarage-thiva',
    authDomain: 'mygarage-thiva.firebaseapp.com',
    storageBucket: 'mygarage-thiva.firebasestorage.app',
  );
}
